name: Test the GitHub Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Integration test
        uses: ./
        id: integration-test-1
        with:
          api-token: ${{ secrets.FP_TOKEN }}
          workspace-id: ${{ secrets.FP_WORKSPACE_ID }}

